### ISSUE TITLE
Block versions wrap a <label> around the radio button and push a "checked" class on the label, not checked="checked" on the radio button

### ISSUE THREAD

**Issue by nesevis** [yapplabs/ember-radio-button#19]
Like the topic says. It seems like a roundabout way to do it.

**Comment by raycohen** [comment]
We are planning implementation changes that rely on `hasBlock`, rather than manually manipulating things inside `wrapInLabelIfUsedAsBlock` as is done now.

I'm not clear if you're also reporting incorrect behavior?  The input created when using a block should have the `checked` property, in addition to the label having a classname `checked`.  Are you seeing different behavior?

**Comment by nesevis** [comment]
The `<input>` doesn't have a checked property; the only thing that occurs on clicks is that the `checked` class is toggled on where I clicked (and off elsewhere).

**Comment by raycohen** [comment]
Keeping the `checked` **property** of the `input` element updated is explicitly under test [here](https://github.com/yapplabs/ember-radio-button/blob/master/tests/unit/components/radio-button-test.js#L52) and other places.

I suspect you are expecting the the `checked` **attribute** to be updated (which would be visible in the DOM inspector), which is not done, intentionally.

These links contain more information:
[jQuery API attributes vs properties](http://api.jquery.com/prop/)
[Notes on property-first setters in ember](http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html#toc_bound-attribute-syntax)

Please reopen if this didn't address your concerns.
