### ISSUE TITLE
Enable closure actions?

### ISSUE THREAD

**Issue by jorgelainfiesta** [yapplabs/ember-radio-button#23]
Hi,

I'm a big fan of closure actions so I enabled them on my local copy by replacing [line 37](https://github.com/yapplabs/ember-radio-button/blob/master/addon/components/radio-button.js#L37) with `this.attrs['changed'](newValue);` and works great. However I don't know how to handle compatibility for others. So I'm here requesting if closure actions could be enabled on a future release of this addon.

Thanks,
Jorge L

**Comment by raycohen** [comment]
I have an app that currently uses closure actions on a component that internally uses `sendAction`.  I thought they just work?  I know the [1.13 blog post](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html) shows using `this.attrs.submit` rather than `this.sendAction('submit')`.  We're on a fairly recent cut of master so maybe that's related.

**Comment by raycohen** [comment]
Looks like it should work based on this commit https://github.com/emberjs/ember.js/commit/7301768fbb14a4ed8e4202e3c42523f5c95e1c84

**Comment by jorgelainfiesta** [comment]
You are absolutely right. Sorry, I just thought it wouldn't work given that the blog post proposed a new syntax. Everything works fine.
